"""Change emotions to JSON

Revision ID: c5ecce2abf89
Revises: e3dbba5e047a
Create Date: 2025-06-14 01:07:00.310573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5ecce2abf89'
down_revision: Union[str, None] = 'e3dbba5e047a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE feedback SET emotions = '[]'")
    op.execute("""
    ALTER TABLE feedback
    ALTER COLUMN emotions
    TYPE JSON
    USING emotions::json
""")
    op.drop_column('feedback', 'emotion_probs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('emotion_probs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.execute("""
    ALTER TABLE feedback
    ALTER COLUMN emotions
    TYPE JSON
    USING emotions::json
""")
    # ### end Alembic commands ###
