"""Add sentiment_label to feedback

Revision ID: debb5ffc2f07
Revises: 4a719953a10b
Create Date: 2025-06-13 16:30:49.617432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'debb5ffc2f07'
down_revision: Union[str, None] = '4a719953a10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('sentiment_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'sentiment_label')
    # ### end Alembic commands ###
