"""add emotions to feedback

Revision ID: e3dbba5e047a
Revises: c1ad4688fa0c
Create Date: 2025-06-13 23:37:09.508713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3dbba5e047a'
down_revision: Union[str, None] = 'c1ad4688fa0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('emotion_probs', postgresql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'emotion_probs')
    # ### end Alembic commands ###
